### PR TITLE
bump version of geekdoc

### PR DESCRIPTION
**Pull request by wkloucek**
Local test worked for me

### CODE REVIEW

**Comment by wkloucek** [comment]
@micbar please approve

**Comment by xoxys** [comment]
https://github.com/owncloud/owncloud.github.io/blob/source/config.yaml#L56

As I said, removed from the theme. I would suggest to remove it here as well to avoid confusions

**Comment by micbar** [comment]
@xoxys @wkloucek the code for the theme is committed also. Is that redundant?
Or do we only run the make target in CI?

**Comment by xoxys** [comment]
Ah right, in the past the theme was committed to the repo. There is no drone step to fetch the theme from the makefile. So you have a) to remove the theme from this repo and add a drone task to fetch it or b) commit the current theme version.

**Comment by wkloucek** [comment]
I did a theme sync. Though it would be nicer to do this in CI. I will ad this to the DevOps Task list. @micbar can you approve / merge?

**Review by xoxys — APPROVED** [review]

**Review by micbar — APPROVED** [review]

**Pull request merged**
