### PR TITLE
Update theme to v0.8.2

### PR DESCRIPTION
**Pull request by LukasHirt**
Changelog:
- [0.8.0](https://github.com/thegeeklab/hugo-geekdoc/releases/tag/v0.8.0)
- [0.8.1](https://github.com/thegeeklab/hugo-geekdoc/releases/tag/v0.8.1)
- [0.8.2](https://github.com/thegeeklab/hugo-geekdoc/releases/tag/v0.8.2)

### CODE REVIEW

**Review by micbar — APPROVED** [review]
LGTM

**Comment by xoxys** [comment]
There will be a new release to fix https://github.com/thegeeklab/hugo-geekdoc/issues/42 during the next days, otherwise LGTM

**Comment by LukasHirt** [comment]
> There will be a new release to fix thegeeklab/hugo-geekdoc#42 during the next days, otherwise LGTM

Thanks for info @xoxys! @micbar Should we then postpone until that release?

**Comment by micbar** [comment]
I vote for postponing now.

**Comment by xoxys** [comment]
@LukasHirt @micbar [v0.8.2](https://github.com/thegeeklab/hugo-geekdoc/releases/tag/v0.8.2) is out. Enjoy

**Comment by LukasHirt** [comment]
> v0.8.2 is out. Enjoy

So fast! :rocket:

@micbar Updated to the newer version :wink:

**Pull request merged**
