### PR TITLE
chore: enable renovate bot

### PR DESCRIPTION
**Pull request by xoxys**
- Enables renovate
- Auto-update the theme in case of `patch` releases
 
As the theme has not reached v1 right now, breaking changes may occur in minor versions already.

### CODE REVIEW

**Comment by xoxys** [comment]
@wkloucek cant add you as reviewer...

**Comment by wkloucek** [comment]
I think would need to run the theme sync too. At least that is what I did the last times. 

https://github.com/owncloud/owncloud.github.io/blob/0e63aeadcf8e5973828e10e87a44fe7b079243d9/Makefile#L7-L10

**Comment by xoxys** [comment]
Oh I remember... Well... I would recommend to **not** commit the theme to the repo. Just download it on the fly during the CI builds https://github.com/owncloud-ansible/owncloud-ansible.github.io/blob/source/.drone.yml

At least, I don't see why the theme hard coded to the repo is a requirement, local downloads and automatic PR testing is still possible with a real-time fetch.

**Comment by wkloucek** [comment]
but we could just add the sync to the drone pipeline!? Should be quite trivial :-D

**Comment by xoxys** [comment]
Added make to CI but I've also removed the theme from the repo, could be very confusing otherwise but your decision :)

**Review by wkloucek — APPROVED** [review]
Looks good :+1:

**Comment by wkloucek** [comment]
> Added make to CI but I've also removed the theme from the repo, could be very confusing otherwise but your decision :)

that how I meant it ;-)

**Comment by wkloucek** [comment]
added PRs to also sync the theme for all of the repos listed here:

https://github.com/owncloud/owncloud.github.io/blob/41dbbf6e42f186171f18af2ac957a72e587c1343/.batchfile#L1-L6

**Pull request merged**
